### ISSUE TITLE
App crashes on pressing globe icon after content load

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1017]
**Describe the bug**
After the content loads in Online tab in Library screen, when the globe icon (menu item) is pressed, the language selection dialog box appears and the app crashes.

**Expected behavior**
The user could select the language and app should not crash.

**Steps to reproduce the behavior:**
1. Open the app and go to the Online tab.
2. Wait till the content loads and then press globe icon.
3. The language selection dialog box appears and app crashes.

**Screenshots**
![content_load_issue](https://user-images.githubusercontent.com/34706326/53223736-50cc3580-3698-11e9-8c83-2caa2cb6d9f6.gif)

**Environment**
- Version of Kiwix Android :  2.4 Build 55
- Device :  Redmi 4
- OS version : Nougat 7.1

**Logs**

2019-02-22 11:39:04.947 24581-24581/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 24581
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 9567216 bytes
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3859)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: android.os.TransactionTooLargeException: data parcel size 9567216 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:622)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3704)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3851)
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6238) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by mhutti1** [comment]
@sonusourav can you git pull and try with the latest master. I think this should have been fixed.

**Comment by sonusourav** [comment]
@mhutti1  I updated and checked it. The bug is still there.
