### ISSUE TITLE
Bug in "Settings" when change Night mode 

### ISSUE THREAD

**Issue by MidoHosny** [kiwix/kiwix-android#1119]
03-24 19:28:06.995 27274-27349/org.kiwix.kiwixmobile E/kiwix: Exception reading article A/Main_Page.html from zim file
    java.io.IOException: write failed: EPIPE (Broken pipe)
        at libcore.io.IoBridge.write(IoBridge.java:455)
        at java.io.FileOutputStream.write(FileOutputStream.java:187)
        at org.kiwix.kiwixmobile.data.ZimContentProvider$TransferThread.run(**ZimContentProvider.java:479**)
     Caused by: libcore.io.ErrnoException: write failed: EPIPE (Broken pipe)
        at libcore.io.Posix.writeBytes(Native Method)
        at libcore.io.Posix.write(Posix.java:202)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
        at libcore.io.IoBridge.write(IoBridge.java:450)
        at java.io.FileOutputStream.write(FileOutputStream.java:187) 
        at org.kiwix.kiwixmobile.data.ZimContentProvider$TransferThread.run(ZimContentProvider.java:479) 
03-24 19:28:09.920 27274-27274/org.kiwix.kiwixmobile E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by MidoHosny** [comment]
https://stackoverflow.com/questions/9039877/android-fragment-screen-rotate

**Comment by kelson42** [comment]
@MidoHosny Could you please confirm this bug is still there with Kiwix for Android 2.5 we have release? I can not reproduce it!

**Comment by macgills** [comment]
I would say we can close this ticket @kelson42

**Comment by kelson42** [comment]
@MidoHosny We believe to have fixed the bug behind the problem you have reported. Please re-open it if you still suffer from the same bug.
