### ISSUE TITLE
Wifi Hotspot service crash

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#1289]
@iadeelzafar 

```
2019-07-14 23:44:28.371 13969-13969/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 13969
    java.lang.RuntimeException: Unable to create service org.kiwix.kiwixmobile.wifi_hotspot.HotspotService: java.lang.SecurityException: Permission Denial: startForeground from pid=13969, uid=10404 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3768)
        at android.app.ActivityThread.access$1400(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=13969, uid=10404 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5062)
        at android.app.Service.startForeground(Service.java:695)
        at org.kiwix.kiwixmobile.wifi_hotspot.HotspotService.onCreate(HotspotService.java:49)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3756)
        at android.app.ActivityThread.access$1400(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:12127)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1289)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:969)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:24800)
        at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11372)
```

**Comment by iadeelzafar** [comment]
This bug was on Android 9 which I was resolved in the latest commit. Can I know when have you installed the APK?

**Comment by kelson42** [comment]
I close as the bug has been fixed.
