### ISSUE TITLE
App Crashes on new install

### ISSUE THREAD

**Issue by iadeelzafar** [kiwix/kiwix-android#1326]
**Steps to reproduce the behavior:**
1.  Run the app on first install from develop branch.
2. App crashes.

P.S: Works fine when opening the app second time.

**Environment**
- Version of Kiwix Android : Develop branch
- Device : Motorola Droid Turbo
- OS version : 6.0

**Logs**
```
    
    --------- beginning of crash
08-02 00:35:35.870 4799-4799/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 4799
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter zimId
        at org.kiwix.kiwixmobile.history.HistoryListItem$HistoryItem.<init>(HistoryListItem.kt)
        at org.kiwix.kiwixmobile.main.MainActivity.webViewUrlFinishedLoading(MainActivity.java:2005)
        at org.kiwix.kiwixmobile.main.KiwixWebViewClient.onPageFinished(KiwixWebViewClient.java:104)
        at ib.d(PG:323)
        at Ae.handleMessage(PG:72)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5491)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by kelson42** [comment]
@iadeelzafar We believe @julianharty might have fixed that bug a few days ago. Are you still able to reproduce it with git develop HEAD?

**Comment by iadeelzafar** [comment]
@kelson42 I can't reproduce it anymore. I think this can be closed now.
