### ISSUE TITLE
Unable to remove Bookmark from bottom bar

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#1359]
**Describe the bug**

I'm unable to remove an item from bookmarks by using the bottom toolbar. Sometimes the app also crashes.

**Expected behavior**

We should be able to remove bookmarks using the bottom toolbar.

**Steps to reproduce the behavior:**
1. Remove an already bookmarked item using the bottom toolbar it remains bookmarked and also appears in the bookmarks activity.

**Environment**
- Version of Kiwix Android : develop
- Device : Redmi Note 3
- OS version : Android M

**Logs**

```
E/MainPresenter: Unable to delete bookmark
    java.lang.IllegalArgumentException: Illegal ID value: 0
        at io.objectbox.Cursor.nativeDeleteEntity(Native Method)
        at io.objectbox.Cursor.deleteEntity(Cursor.java:199)
        at io.objectbox.Box.remove(Box.java:445)
        at org.kiwix.kiwixmobile.database.newdb.dao.NewBookmarksDao.deleteBookmark(NewBookmarksDao.kt:61)
        at org.kiwix.kiwixmobile.data.Repository$deleteBookmark$1.run(Repository.kt:113)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by macgills** [comment]
Why didn't this issue auto close when the pr was merged? @kelson42 ?

**Comment by mhutti1** [comment]
I don't think the pr was merged?

**Comment by macgills** [comment]
Wow, how dumb of me

**Comment by macgills** [comment]
would I have gotten the delete branch prompt if I just closed it? I feel like my internet has been messing me around today, comments not appearing and the like
