### ISSUE TITLE
Random button works... randomly

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1396]
There is a couple of instances where clicking the random button will not open a new article (android 9 / 2.5.3). This actually happens a lot more often with the 3.0 nightly.

**Comment by macgills** [comment]
Successful random article
```
2019-08-22 16:33:46.814 11849-11849/org.kiwix.kiwixmobile D/kiwix: openRandomArticle: A/Zeta_(Dark)_Lore.html
2019-08-22 16:33:46.816 564-5128/? D/audio_route: Apply path: speaker-protected
2019-08-22 16:33:46.821 564-5128/? D/audio_hw_primary: enable_snd_device: snd_device(95: vi-feedback)
2019-08-22 16:33:46.821 564-5128/? D/audio_route: Apply path: vi-feedback
2019-08-22 16:33:46.821 564-5128/? D/audio_hw_primary: enable_audio_route: usecase(24) apply and update mixer path: spkr-vi-record
2019-08-22 16:33:46.821 564-5128/? D/audio_route: Apply path: spkr-vi-record
2019-08-22 16:33:46.846 564-5128/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
2019-08-22 16:33:46.846 564-5128/? D/audio_route: Apply path: low-latency-playback
2019-08-22 16:33:46.849 11849-12393/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/A/Zeta_(Dark)_Lore.html
2019-08-22 16:33:46.854 11849-11930/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/A/Zeta_(Dark)_Lore.html = text/html
2019-08-22 16:33:46.884 564-5128/? E/msm8974_platform: ramp_speaker_gain: Could not get ctl for mixer cmd - Left Speaker Gain or Right Speaker Gain, not applying speaker gain ramp
2019-08-22 16:33:46.884 564-5128/? D/audio_hw_primary: out_write: retry previous failed cal level set
2019-08-22 16:33:46.954 11849-12517/org.kiwix.kiwixmobile D/kiwix: reading  A/Zeta_(Dark)_Lore.html(mime: text/html, size: 56324) finished.
2019-08-22 16:33:46.966 11849-12393/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/style.css
2019-08-22 16:33:46.970 11849-12521/org.kiwix.kiwixmobile D/kiwix: reading  -/s/style.css(mime: text/css, size: 140) finished.
2019-08-22 16:33:46.972 11849-12516/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/ext.Tabber.css
2019-08-22 16:33:46.972 11849-12519/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/mediawiki.toc.css
2019-08-22 16:33:46.974 11849-12393/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jsConfigVars.js
2019-08-22 16:33:46.980 11849-12519/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.js
2019-08-22 16:33:46.983 11849-12516/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.Tabber.js
2019-08-22 16:33:46.983 11849-12393/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/site.js
2019-08-22 16:33:46.988 11849-12520/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/startup.js
2019-08-22 16:33:46.995 11849-11930/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/style.css = text/css
2019-08-22 16:33:46.997 11849-12524/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/mediawiki.toc.css(mime: text/css, size: 162) finished.
2019-08-22 16:33:47.000 11849-12523/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js
2019-08-22 16:33:47.003 11849-11930/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/mediawiki.toc.css = text/css
2019-08-22 16:33:47.007 11849-12522/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.toc.js
2019-08-22 16:33:47.008 11849-12525/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/jsConfigVars.js(mime: application/javascript, size: 1649) finished.
2019-08-22 16:33:47.013 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jsConfigVars.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.015 11849-12526/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/ext.Tabber.css(mime: text/css, size: 162) finished.
2019-08-22 16:33:47.022 11849-12528/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/site.js(mime: application/javascript, size: 162) finished.
2019-08-22 16:33:47.023 11849-11930/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/ext.Tabber.css = text/css
2019-08-22 16:33:47.028 11849-12529/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/startup.js(mime: application/javascript, size: 162) finished.
2019-08-22 16:33:47.029 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.Tabber.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.038 11849-12527/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/ext.Tabber.js(mime: application/javascript, size: 162) finished.
2019-08-22 16:33:47.043 11849-12532/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/mediawiki.toc.js(mime: application/javascript, size: 162) finished.
2019-08-22 16:33:47.043 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/site.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.043 11849-12530/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/jquery.js(mime: application/javascript, size: 162) finished.
2019-08-22 16:33:47.044 11849-12531/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/mediawiki.js(mime: application/javascript, size: 382) finished.
2019-08-22 16:33:47.050 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/startup.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.053 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.056 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.059 11849-11930/org.kiwix.kiwixmobile W/ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.toc.js (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)
2019-08-22 16:33:47.162 11849-11996/org.kiwix.kiwixmobile D/OpenGLRenderer: endAllActiveAnimators on 0x74facd2400 (MenuPopupWindow$MenuDropDownListView) with handle 0x74fa6765e0
2019-08-22 16:33:47.232 11849-11849/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/startup.js (1)
2019-08-22 16:33:47.234 11849-11849/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js (1)
2019-08-22 16:33:47.234 11849-11849/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.js (1)
2019-08-22 16:33:47.235 11849-11849/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/site.js (1)
2019-08-22 16:33:47.235 11849-11849/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.Tabber.js (1)
2019-08-22 16:33:47.236 11849-11849/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.toc.js (1)
2019-08-22 16:33:47.248 11849-11849/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/Zeta_(Dark)_Lore.html
2019-08-22 16:33:47.249 11849-11849/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/Zeta_(Dark)_Lore.html
```
Unsuccessful random article
```
2019-08-22 16:32:22.476 11849-11849/org.kiwix.kiwixmobile D/kiwix: openRandomArticle: A/Leviathan_Showdown.html
2019-08-22 16:32:22.479 564-5128/? D/audio_route: Apply path: speaker-protected
2019-08-22 16:32:22.483 564-5128/? D/audio_hw_primary: enable_snd_device: snd_device(95: vi-feedback)
2019-08-22 16:32:22.483 564-5128/? D/audio_route: Apply path: vi-feedback
2019-08-22 16:32:22.483 564-5128/? D/audio_hw_primary: enable_audio_route: usecase(24) apply and update mixer path: spkr-vi-record
2019-08-22 16:32:22.483 564-5128/? D/audio_route: Apply path: spkr-vi-record
2019-08-22 16:32:22.509 564-5128/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
2019-08-22 16:32:22.509 564-5128/? D/audio_route: Apply path: low-latency-playback
2019-08-22 16:32:22.513 11849-12393/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/A/Leviathan_Showdown.html
2019-08-22 16:32:22.518 11849-11930/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/A/Leviathan_Showdown.html = text/html
2019-08-22 16:32:22.546 564-5128/? E/msm8974_platform: ramp_speaker_gain: Could not get ctl for mixer cmd - Left Speaker Gain or Right Speaker Gain, not applying speaker gain ramp
2019-08-22 16:32:22.546 564-5128/? D/audio_hw_primary: out_write: retry previous failed cal level set
2019-08-22 16:32:22.616 11849-12461/org.kiwix.kiwixmobile D/kiwix: reading  A/Leviathan_(Raid).html(mime: text/html, size: 91719) finished.
2019-08-22 16:32:22.623 11849-11849/org.kiwix.kiwixmobile W/ContentUriUtils: Cannot open content uri: content://org.kiwix.kiwixmobile.zim.base/A/Leviathan_Showdown.html
    java.lang.RuntimeException: Operation not supported
        at org.kiwix.kiwixmobile.data.ZimContentProvider.query(ZimContentProvider.java:423)
        at android.content.ContentProvider.query(ContentProvider.java:1057)
        at android.content.ContentProvider.query(ContentProvider.java:1149)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at org.chromium.base.ContentUriUtils.a(PG:61)
        at org.chromium.base.ContentUriUtils.maybeGetDisplayName(PG:89)
        at org.chromium.content.browser.webcontents.WebContentsImpl.nativeGetTitle(Native Method)
        at org.chromium.content.browser.webcontents.WebContentsImpl.m(PG:75)
        at org.chromium.android_webview.AwContents.r(PG:636)
        at aIE.loadingStateChanged(PG:135)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-08-22 16:32:22.637 11849-11849/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/Leviathan_Showdown.html
2019-08-22 16:32:22.638 11849-11849/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/Leviathan_Showdown.html
```

**Comment by vertigo220** [comment]
Love the title. So, a couple things I've noticed in testing this out are that the blue loading bar across the top shows every time, regardless of whether it actually loads a new article or not and it seems to work a bit more consistently (though still only about 50% of the time) when either hitting the random button every second or so or every 10 seconds, whereas doing it every ~4 seconds seems to only work maybe 20% of the time. I only did it for a few minutes, so I can't say if those odds would level out over time, but there definitely seems to be a difference. This is also seen in that, if you wait a few seconds, then start hitting it repeatedly, it will often take a few taps before it loads an article, but then almost every tap after will load a new one, rapidly switching between them. I tested two different size files for the same content and the results were the same, so doesn't seem based on file size.

**Comment by macgills** [comment]
Unsuccessful load after a dummy cursor returned on ContentProvider query
```
2019-09-06 10:14:26.056 9179-9179/org.kiwix.kiwixmobile D/kiwix: openRandomArticle: A/The_New_Skyfarer_Special.html
2019-09-06 10:14:26.121 9179-9895/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/A/The_New_Skyfarer_Special.html
2019-09-06 10:14:26.123 9179-9296/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/A/The_New_Skyfarer_Special.html = text/html
2019-09-06 10:14:26.216 9179-9944/org.kiwix.kiwixmobile D/kiwix: reading  A/New_Skyfarer_Special_January_2018.html(mime: text/html, size: 17809) finished.
2019-09-06 10:14:26.240 9179-9179/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/The_New_Skyfarer_Special.html
2019-09-06 10:14:26.240 9179-9179/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/The_New_Skyfarer_Special.html
2019-09-06 10:14:26.241 9179-9179/org.kiwix.kiwixmobile D/kiwix: invalidUrl = false
```
`2019-09-06 10:14:26.216 9179-9944/org.kiwix.kiwixmobile D/kiwix: reading  A/New_Skyfarer_Special_January_2018.html(mime: text/html, size: 17809) finished.`  this line I think may be of special interest as we were told to load `A/The_New_Skyfarer_Special.html` but actually read `A/New_Skyfarer_Special_January_2018.html`

Is it possible that 
```
public native boolean getRandomPage(JNIKiwixString var1);
```
Is returning a article that doesn't exist?

the pattern certainly repeats for all failed randoms I have observed
```
2019-09-06 10:22:11.121 9179-9179/org.kiwix.kiwixmobile D/kiwix: openRandomArticle: A/Pina_Hazard.html
2019-09-06 10:22:11.149 9179-10431/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/A/Pina_Hazard.html
2019-09-06 10:22:11.151 9179-9296/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/A/Pina_Hazard.html = text/html
2019-09-06 10:22:11.241 9179-10504/org.kiwix.kiwixmobile D/kiwix: reading  A/Cinderella_Fantasy:_Piña_Hazard.html(mime: text/html, size: 146370) finished.
```
@mhutti @mgautierfr would be curious to hear your opinion

**Comment by mgautierfr** [comment]
It is possible that getRandomPage "returns" a redirection article. I don't know if android, within this specific code path handles it correctly.

**Comment by macgills** [comment]
```
    /**
     * Give the host application a chance to take over the control when a new
     * url is about to be loaded in the current WebView. If WebViewClient is not
     * provided, by default WebView will ask Activity Manager to choose the
     * proper handler for the url. If WebViewClient is provided, return {@code true}
     * means the host application handles the url, while return {@code false} means the
     * current WebView handles the url.
     *
     * <p>Notes:
     * <ul>
     * <li>This method is not called for requests using the POST &quot;method&quot;.</li>
     * <li>This method is also called for subframes with non-http schemes, thus it is
     * strongly disadvised to unconditionally call {@link WebView#loadUrl(String)}
     * with the request's url from inside the method and then return {@code true},
     * as this will make WebView to attempt loading a non-http url, and thus fail.</li>
     * </ul>
     *
     * <p>This method is called only if {@link WebViewFeature#SHOULD_OVERRIDE_WITH_REDIRECTS} is
     * supported. You can check whether that flag is supported using {@link
     * WebViewFeature#isFeatureSupported(String)}.
     *
     * @param view The WebView that is initiating the callback.
     * @param request Object containing the details of the request.
     * @return {@code true} if the host application wants to leave the current WebView
     *         and handle the url itself, otherwise return {@code false}.
     */
 @Override
  public boolean shouldOverrideUrlLoading(WebView view, String url) {
    callback.webViewUrlLoading();

    if (ZimContentProvider.isRedirect(url)) {
      view.loadUrl(ZimContentProvider.getRedirect(url));
      return true;
    }
```
I think it should be? I don't think the codepath is different than the normal article load?

**Comment by macgills** [comment]
More context:
```
  private void openRandomArticle() {
    String articleUrl = ZimContentProvider.getRandomArticleUrl();
    Log.d(TAG_KIWIX, "openRandomArticle: " + articleUrl);
    openArticle(articleUrl);
  }
```
```
  private void openArticle(String articleUrl) {
    if (articleUrl != null) {
      getCurrentWebView().loadUrl(
        Uri.parse(ZimContentProvider.CONTENT_URI + articleUrl).toString());
    }
  }
```
```
  public static String getRedirect(String url) {
    return Uri.parse(CONTENT_URI + currentJNIReader.checkUrl(getFilePath(Uri.parse(url))))
        .toString();
  }

  public static boolean isRedirect(String url) {
    return !url.equals(getRedirect(url));
  }
```

I could try adding redirect checking to the randomArticle call and report back?

**Comment by kelson42** [comment]
@macgills Yes, if redirect... the webview should redirect...

**Comment by macgills** [comment]
Right, I have a fix, apparently the original redirect code only works when using the in browser navigation. Thanks a lot for your time @mgautierfr
