### ISSUE TITLE
Opening a zim file results in a crash

### ISSUE THREAD

**Issue by abdulwd** [kiwix/kiwix-android#1560]
**Describe the bug**

Opening a zim file crashes the app.

**Expected behavior**

No crash

**Steps to reproduce the behavior:**
1. Make a fresh install of the kiwix app
2. Download a new zim file and open

**Environment**
- Version of Kiwix Android : develop
- Device : Redmi Note 3
- OS version : Pixel Experience Android 9

**Logs**
```
2019-10-21 14:36:07.709 23349-23349/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 23349
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=org.kiwix.kiwixmobile.core.main.CoreMainActivity dat=file:///storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files/Kiwix/psiram_en_all_nopic_2019-04.zim pkg=org.kiwix.kiwixmobile }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
        at android.app.Activity.startActivityForResult(Activity.java:4587)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4545)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4906)
        at android.app.Activity.startActivity(Activity.java:4874)
        at org.kiwix.kiwixmobile.core.main.CoreMainActivity.open(CoreMainActivity.java:1853)
        at org.kiwix.kiwixmobile.core.main.CoreMainActivity.lambda$onCreate$1$CoreMainActivity(CoreMainActivity.java:374)
        at org.kiwix.kiwixmobile.core.main.-$$Lambda$CoreMainActivity$lTl_sirDrsY5VSqvdhIg7v-IPRY.invoke(Unknown Source:4)
        at org.kiwix.kiwixmobile.core.zim_manager.fileselect_view.adapter.BookOnDiskViewHolder$BookViewHolder$bind$3.onClick(BooksOnDiskViewHolder.kt:101)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25906)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kelson42** [comment]
@macgills @abdulwd Could you please have a look on top prio to that one?

**Comment by macgills** [comment]
Yeah we just need to update `app/AndroidManifest.xml` with the correct intentfilter

**Comment by kelson42** [comment]
@macgills I don't understand why this is wrong in a first place?

**Comment by macgills** [comment]
Modularisation. There are now 2 MainActivities and they need to be addressed differently.
Basically how we open a file right now is very dumb and it closes the entire activity, relaunching it with a new intent. I am in the process of changing it to be not so destructive.
Nobody is impacted because this is on develop

**Comment by kelson42** [comment]
@macgills @abdulwd just realized this in on develop... And this was written. That said, this should not happen, the CI should detect such a problem.

**Comment by macgills** [comment]
That would be the case if we had zim file opening tests, those were disabled due to flakiness
