### ISSUE TITLE
App crashing on pressing back button in Notes

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1886]
**Describe the bug**

When someone presses the back button in the Notes page, app crashes.

**Expected behavior**

The notes should be saved and the page should leave the screen.

**Steps to reproduce the behavior:**
1. Click on the Notes option.
2. Click the back button.
3. App crashes.

**Screenshots**

[Link](https://imgur.com/gBWWDVz)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi 4
- OS version : Nougat

**Logs**

2020-03-12 15:03:03.575 1510-1718/? E/WifiHAL: Received fatal event, sending alert
2020-03-12 15:05:41.115 22459-22459/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 22459
    java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Dialog org.kiwix.kiwixmobile.core.utils.DialogShower.create(org.kiwix.kiwixmobile.core.utils.KiwixDialog, kotlin.jvm.functions.Function0[])' on a null object reference
        at org.kiwix.kiwixmobile.core.main.ConfirmationAlertDialogFragment.onCreateDialog(ConfirmationAlertDialogFragment.java:65)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:403)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1484)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by kelson42** [comment]
I can not reproduce the bug on my Android 10, so would be great if you could fix this one as well... otherwise might be difficult to reproduce for an other dev.

**Comment by Dalakoti07** [comment]
@sonusourav are working on this issue, I also observed that app crashes, when back button pressed while taking notes, but this behaviour is non-deterministic, I did it 5 times, but app crashed only 1 time.

Please tell if you are working.

**Comment by sonusourav** [comment]
Hey @Dalakoti07 I am working on this issue.

**Comment by Dalakoti07** [comment]
ok
Thanks for informing
