### ISSUE TITLE
TextToSpeech Pause/Stop buttons no longer visible and subsequent read alouds cause a crash

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2364]
**Describe the bug**
The buttons do not appear and I got the folllowing crash testing the feature
```
2020-09-07 08:48:00.385 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 15093
    java.lang.NullPointerException: Attempt to read from field 'org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech$TTSTask org.kiwix.kiwixmobile.core.main.KiwixTextToSpeech.currentTTSTask' on a null object reference
        at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.lambda$setUpTTS$3$CoreReaderFragment(CoreReaderFragment.java:683)
        at org.kiwix.kiwixmobile.core.main.-$$Lambda$CoreReaderFragment$dJ7yV3A9jJPxjfun6ekvjOK-1AA.onAudioFocusChange(Unknown Source:2)
        at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2144)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Expected behavior**
Read aloud to be controlled by in app UI and to be free of crashes

**Steps to reproduce the behavior:**
1. Open a zim file
1. click read aloud from the overflow menu
1. hear the contents being read but see no UI for controlling it
1. press back until you exit the app
1. re-launch application and repeat steps 1&2
1. crash

**Screenshots**

**Environment**
- Version of Kiwix Android : develop
- Device : nexus5x
- OS version : 8.1

**Comment by gouri-panda** [comment]
@macgills Can I take this issue?
