### ISSUE TITLE
Index Out of Bounds Exception on Custom App

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2542]
**Describe the bug**
```
    Exception Details:
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixcustomwikimed/org.kiwix.kiwixmobile.custom.main.CustomMainActivity}: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at java.util.ArrayList.get(ArrayList.java:411)
at org.kiwix.kiwixmobile.custom.main.CustomReaderFragment.onViewCreated(CustomReaderFragment.kt:35)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:115)
at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:129)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:362)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at org.kiwix.kiwixmobile.core.main.CoreMainActivity.onStart(CoreMainActivity.kt:1)
at org.kiwix.kiwixmobile.custom.main.CustomMainActivity.onStart(CustomMainActivity.kt:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
at android.app.Activity.performStart(Activity.java:6973)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
.
```

**Environment**
Device:[on5xelte]
Model:[SM-G570F]
Manufacturer:[samsung]
Time:[1513227951000]
Android Version:[7.0]
App Version:[2020-11 5203070]

Not immediately sure which version of the app this is based as it is a custom app, potentially already fixed

**Comment by kelson42** [comment]
@abdulwd Do we know if this crash scenario still occur, should be visible in the play store admin.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I am not able to reproduce this bug.

**Comment by kelson42** [comment]
@MohitMaliFtechiz This comes from the play store. Have you checked there?

**Comment by MohitMaliFtechiz** [comment]
yes i tried playstore build.

**Comment by kelson42** [comment]
@MohitMaliFtechiz It's not what I mean I mean we should check playstore reports.

**Comment by julianharty** [comment]
@kelson42 @MohitMaliFtechiz I've checked the PlayStore reports in Android Vitals and reviewed the crash clusters for the most popular of the Kiwix family of apps: (Chemistry and Physics simulation, Kiwix - even though it's not a custom app, WikiMed (English), WikiMed (Arabic), WikiMed (French), WikiMed (mini), WikiMed (Spanish), WikiMed (Chinese), and WikiMed (German). Of these the last 2 didn't have any Android Vitals statistics as the overall usage volumes are too small.

I can't see this crash in any of the reports. So if it's happening at all, it's so infrequent I recommend this issue is closed. There are other crashes and ANRs worth addressing first.

**Comment by kelson42** [comment]
@julianharty Thank you very much for checking this.
