### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#258]
_From @eileenfan on September 10, 2017 11:29_

//package name: org.kiwix.kiwixmobile
//version: 1.96
 java.lang.NullPointerException
 	at org.kiwix.kiwixmobile.KiwixWebView.performLongClick(KiwixWebView.java:176)
 	at android.webkit.WebViewClassic$PrivateHandler.handleMessage(WebViewClassic.java:7402)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

_Copied from original issue: kiwix/kiwix-xulrunner#485_

**Comment by kelson42** [comment]
@eileenfan I suspect this is with version 2.2?

**Comment by kelson42** [comment]
We believe this bug has been fixed in later versions
