### ISSUE TITLE
Cannot read zimit-generated files anymore

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2661]
Running Android 3.4.4 build 6230404 and ran https://farm.youzim.it/pipeline/a4c6828d8bb6b108d13a8a06 on Zimit. No error message, just the little round thing going round and round for ever as it tries to open the file.

Might be a regression on the zimit side, haven't tested with other zim files yet.

**Comment by gouri-panda** [comment]
This happens on my android 6 emulator.

**Comment by Popolechien** [comment]
Can confirm it happens on other zim files from zimit.

**Comment by kelson42** [comment]
@Popolechien what is your android version?

**Comment by Popolechien** [comment]
@kelson42 Android 9 running on Huawei p20 Lite

**Comment by kelson42** [comment]
@gouri-panda OK, so the whole ZIMIT (service worker base) rendering is broken, even on Android10/11? Please test with https://download.kiwix.org/zim/zimit/musictheory.net_en_all_2021-03.zim

**Comment by gouri-panda** [comment]
>@gouri-panda OK, so the whole ZIMIT (service worker base) rendering is broken, even on Android10/11? Please test with https://download.kiwix.org/zim/zimit/musictheory.net_en_all_2021-03.zim

I checked the zim file you suggested.Physical android 10 and android 11 both are fine. but android 6 is not rendering the web.
```
I/art: Not late-enabling -Xcheck:jni (already on)
W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
W/System.err:     at org.kiwix.kiwixmobile.core.CoreApp.$jacocoInit(CoreApp.kt)
W/System.err:     at org.kiwix.kiwixmobile.core.CoreApp.<clinit>(CoreApp.kt)
W/System.err:     at java.lang.Class.newInstance(Native Method)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:996)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
W/System.err: Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
W/System.err:     at libcore.io.Posix.open(Native Method)
W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
W/System.err: 	... 21 more
I/MultiDex: VM with version 2.1.0 has multidex support
```

**Comment by kelson42** [comment]
@Popolechien Can you please regenerate the zim file and try again? I believe it might be related to the problem we had with the zstd compression.

**Comment by Popolechien** [comment]
Yes, all good now.
