### ISSUE TITLE
Introductory screen hangs if the user navigates away and then returns to the app

### ISSUE THREAD

**Issue by Fs00** [kiwix/kiwix-android#2730]
**Describe the bug**
If the user navigates away from Kiwix (e.g. switches to another app) when the introductory screen is shown, then Kiwix will hang irreversibly upon returning back to it.

**Expected behavior**
After returning to the app, the user should be able to interact with the UI and continue the intro.

**Steps to reproduce the behavior:**
1. Open the newly installed Kiwix app, the "Welcome..." message should be shown
2. Switch to another app
3. Go back to Kiwix
4. Observe the hang

**Environment**
- Version of Kiwix Android: 3.4.5
- Device: Samsung A3 2017 & Sony Xperia X Compact
- OS version: Android 9 & 10 (LineageOS)

**Logs**
When the app hangs, this error gets printed to logcat:
```
FATAL EXCEPTION: main
Process: org.kiwix.kiwixmobile, PID: 21153
java.lang.IllegalArgumentException: Navigation action/destination org.kiwix.kiwixmobile:id/action_readerFragment_to_introFragment cannot be found from the current destination Destination(org.kiwix.kiwixmobile:id/introFragment) label=IntroFragment class=org.kiwix.kiwixmobile.intro.IntroFragment
	at androidx.navigation.NavController.navigate(NavController.java:55)
	at org.kiwix.kiwixmobile.core.main.CoreMainActivity.navigate(CoreMainActivity.kt:3)
	at org.kiwix.kiwixmobile.main.KiwixMainActivity.onStart(KiwixMainActivity.kt:6)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7847)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by 4shutosh** [comment]
@Fs00 Thank you for raising the issue.
The Exception seems legit that will create the screen to hang.
Will come back once I am able to reproduce this.

**Comment by gouri-panda** [comment]
@4shutosh  Thanks! Reproducing the issue would be great. But I think the error is here for wrong arguments that are passing in intent action.

**Comment by cdhiraj40** [comment]
@gouri-panda I think its happening cause of 
```
    if (sharedPreferenceUtil.showIntro()) {
      navigate(KiwixReaderFragmentDirections.actionReaderFragmentToIntroFragment())
    }
    ``` 
    we are setting it true just after showing, I think it we should be showing this after we click on the ``Get Started`` button.

**Comment by gouri-panda** [comment]
@cdhiraj40 Yes we do! Take a look at the code.
```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState)
    get_started.setOnClickListener { navigateToLibrary() }
```
Here we are setting with Get Started button.
```  
private fun navigateToLibrary() {
    dismissAutoRotate()
    presenter.setIntroShown()
    findNavController().navigate(IntroFragmentDirections.actionIntrofragmentToLibraryFragment())
  }
```
Here we are setting setIntroShown() with the presenter.

**Comment by MohitMaliFtechiz** [comment]
Hi,

This scenario was crashing on android 9 and android 8, I have placed the fix.
