### ISSUE TITLE
Kiwix crashes when library_zim.xml only contains a few items

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#320]
I accidentally discovered that as yet unknown problems in the content of `library_zim.xml` causes the entire app to crash with an obscure long stack trace related to the UI. After discussion with @mhutti1 it appears that LibraryNetworkEntity.java is failing to parse the contents of this file and that's then probably returning an empty list of `book` objects which then causes the UI code to do stupid things...

```
Here for completeness is the stack trace
12-14 17:04:24.911 24723 24723 D AndroidRuntime: Shutting down VM
12-14 17:04:24.913 24723 24832 I kiwix   : Opening ZIM file /storage/emulated/0/Kiwix/wikipedia_en_for-schools_2013-01.zimaa
12-14 17:04:24.913 24723 24723 E AndroidRuntime: FATAL EXCEPTION: main
12-14 17:04:24.913 24723 24723 E AndroidRuntime: Process: org.kiwix.kiwixmobile, PID: 24723
12-14 17:04:24.913 24723 24723 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getImportantForAccessibility()' on a null object reference
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2363)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:1876)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:702)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.ListView.fillFromTop(ListView.java:763)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1671)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.View.layout(View.java:16636)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-14 17:04:24.913 24723 24723 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:
12-14 17:04:24.916   650  1509 W ActivityManager:   Force finishing activity org.kiwix.kiwixmobile/.zim_manager.ZimManageActivity
12-14 17:04:24.920   650  1509 W ActivityManager:   Force finishing activity org.kiwix.kiwixmobile/.KiwixMobileActivity
12-14 17:04:24.937 24723 24832 I kiwix   : Opening ZIM file /storage/emulated/0/Kiwix/wikipedia_en_bollywood_2017-02.zim
```

**Comment by julianharty** [comment]
I've revised the title now I understand what the cause of the crash was, a bug in the code that populates the content for the GUI. It happened to be triggered when the library only contained 1 item. I expect it would have happened with 2, 3, or 4 items, etc. whatever could fit into a screen of content. It might have triggered by scrolling to the bottom of a longer set of items too. I'll close this issue once the code has been merged.
