### ISSUE TITLE
Clicking on external link returns error message (Android 13)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3279]
Sent by a user via email, let me know if info is missing:

Galaxy S20+5G, SM-G986B/DS, One UI-Version 5.1, Android 13;
 
Using Wikipedia_de_all_maxi_2023-01-09

"Geographic coordinates (of a location) cannot be copied from Kiwix and a window with apps to be selected (e.g. google Maps, OSMand, etc.) does not appear. This worked fine with Kiwix on my previous device (Samsung S10). Instead, the following message appears: "No apps could be installed for this data...." (the rest cannot be read even in landscape format, the message window does not increase in size).

![Screenshot_20230316_112437_Kiwix](https://user-images.githubusercontent.com/21675885/226312238-8a0d721f-688b-4dfe-ac34-5a4ab27a988b.jpg)

**Comment by gouri-panda** [comment]
@Popolechien Thanks! Do we have any logs about this user's device?

**Comment by Popolechien** [comment]
@gouri-panda No log.
@kelson42 Yeah I think so too but I'm surprised that they would say it worked before and not anymore.

**Comment by gouri-panda** [comment]
@kelson42 Sorry! Not yet. I haven't tried yet. I'll try it.

**Comment by gouri-panda** [comment]
@kelson42 Yes! But in my case, it crashes. 
<details><Summary>Logs</summary> 

```

AndroidRuntime          org.kiwix.kiwixmobile                E  FATAL EXCEPTION: main
                                                                                                    Process: org.kiwix.kiwixmobile, PID: 20108
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:642)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
                                                                                                    Caused by: java.net.MalformedURLException: unknown protocol: geo
                                                                                                    	at java.net.URL.<init>(URL.java:608)
                                                                                                    	at java.net.URL.<init>(URL.java:498)
                                                                                                    	at java.net.URL.<init>(URL.java:447)
                                                                                                    	at org.kiwix.kiwixmobile.core.utils.ExternalLinkOpener.requestOpenLink(ExternalLinkOpener.kt:64)
                                                                                                    	at org.kiwix.kiwixmobile.core.utils.ExternalLinkOpener.openExternalUrl(ExternalLinkOpener.kt:42)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.openExternalUrl(CoreReaderFragment.kt:1203)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreWebViewClient.shouldOverrideUrlLoading(CoreWebViewClient.kt:73)

```

</details>

**Comment by kelson42** [comment]
@gouri-panda Thank you for testing. This is a really bad news, a strong regression on one of the most basic feature... Can wait to read the explanation, fix and automated test.
