### ISSUE TITLE
File transfer feature does not work in android 12, android 13.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3491]
**Describe the bug**
While testing #1532 I have seen a bug. The file transfer feature does not work in Android 12 and Android 13. It has failed to connect to the receiver/sender.

**Expected behavior**
It should transfer the files.

**Steps to reproduce the behavior:**
* Install apk from the develop branch.
* Open File Transfer feature.
* Click on the search button to find nearby devices.
* You will see the error.

**Environment**
- Version of Kiwix Android: 3.7.1
- Device: Redmi Note 9 and Google Pixel 6a.
- OS version: Android 12, Android 13.

**Redmi Note 9(Android 12)**

https://github.com/kiwix/kiwix-android/assets/34593983/a4170e96-c294-45e6-8b3c-c48d0b618863

**Google Pixel 6a(Android 13)**

https://github.com/kiwix/kiwix-android/assets/34593983/60a4f6b0-d4e9-4e2b-9208-4311a36a9379

**Logs for android 13**
```
Attempt to cast generated internal exception:                                                                         android.os.BadTypeParcelableException: Parcelable creator
android.net.wifi.p2p.WifiP2pDevice is not a subclass of required class Landroid.os.Parcelable; provided in the parameter
at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4925)
at android.os.Parcel.readParcelableInternal(Parcel.java:4807)
at android.os.Parcel.readValue(Parcel.java:4567)
at android.os.Parcel.readValue(Parcel.java:4347)
at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
at android.os.Parcel$LazyValue.apply(Parcel.java:4445)
at android.os.Parcel$LazyValue.apply(Parcel.java:4404)
at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
at android.os.BaseBundle.getValue(BaseBundle.java:374)
at android.os.Bundle.getParcelableArray(Bundle.java:1020)
at android.content.Intent.getParcelableArrayExtra(Intent.java:8991)
at org.kiwix.kiwixmobile.localFileTransfer.KiwixWifiP2pBroadcastReceiver.onReceive(KiwixWifiP2pBroadcastReceiver.kt:62) 
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Starting handshake
PeerGroupHandshake      org.kiwix.kiwixmobile                D  Handshake in progress
WifiDirectManager       org.kiwix.kiwixmobile                D  InetAddress is null
```

**For Redmi note 9 (Android 12)**
```
 Starting handshake
PeerGroupHandshake      org.kiwix.kiwixmobile                D  Handshake in progress
WifiDirectManager       org.kiwix.kiwixmobile                D  InetAddress is null
```

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please write a test for this please
