### ISSUE TITLE
Application crashes when opening saved notes if the ZIM file does not exist. 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3682]
**Describe the bug**
The application crashes when opening saved notes if the ZIM file does not exist. 

**Expected behavior**
Instead of crashing it should not open the note and show a toast message that the zim file is not found like it is showing when we are trying to open the article.

**Steps to reproduce the behavior:**
1. Save note.
2. Delete the zim file.
3. Open the Notes screen.
4. Click on the saved note and then click `Open Note` you will see the crash.

**Environment**
- Version of Kiwix Android: 3.9.1
- Device: Any device
- OS version: Any OS

**Logs**

```kotlin
java.lang.IllegalStateException: Fragment AddNoteDialog{e13576b} (1d1493c1-8edd-4faa-9c39-30468b1a7f4f tag=AddNoteDialog) did not return a View from onCreateView() or this was called before onCreateView().                                                                                             
```

```kotlin
FATAL EXCEPTION: main
Process: org.kiwix.kiwixmobile, PID: 3807
kotlin.UninitializedPropertyAccessException: lateinit property articleNoteFileName has not been initialized
at org.kiwix.kiwixmobile.core.main.AddNoteDialog.displayNote(AddNoteDialog.kt:414)
at org.kiwix.kiwixmobile.core.main.AddNoteDialog.onViewCreated(AddNoteDialog.kt:285)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8194)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by kelson42** [comment]
WOW :(

**Comment by MohitMaliFtechiz** [comment]
@kelson42 IMO custom apps should not crash because of this. Custom apps only have a single file in them and now we are using the `fileDescriptor` which does not have any path in it so we are not setting again it to the `ZimFileReader`, so this is not crash because of this issue.

https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/core/src/main/java/org/kiwix/kiwixmobile/core/page/notes/viewmodel/effects/ShowOpenNoteDialog.kt#L51

**Comment by kelson42** [comment]
@MohitMaliFtechiz Hope all of this kind of low level related vanish (only in one place available) with your "one reader" PR.
