### ISSUE TITLE
Remove custom LayoutInflatorFactory for custom fonts

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#37]
_From @rashiq on June 8, 2016 11:30_

Kiwix uses custom fonts to render unsupported Languages (see LanguageUtils.java). 
But the custom language-changer solution is now a bit outdated. Replace the font changing with the library [Calligraphy](https://github.com/chrisjenx/Calligraphy).

_Copied from original issue: kiwix/kiwix#56_

**Comment by kelson42** [comment]
As we need to re-evaluate the support of "exotic" languages anyway in 3.1. Lets put it here.

See also #1222 #207

**Comment by kelson42** [comment]
This is a bit outdated but seems to work fine for the moment. Not a priority to improve IMO.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please update the ticket and if it still make sense, then we should implement it.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 , i have tested it and find some important things.

* Yes we should replace this because this code is not working in my device(Redmi note 9 **Android 12**) .


   **Logs**

`
   Font Change Failed: Could not access private field of the LayoutInflater
    java.lang.NoSuchFieldException: No field mFactorySet in class Landroid/view/LayoutInflater; (declaration of 'android.view.LayoutInflater' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at org.kiwix.kiwixmobile.core.utils.LanguageUtils.changeFont(LanguageUtils.kt:96)
        at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.handleLocaleCheck(CoreReaderFragment.kt:795)
        at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.onViewCreated(CoreReaderFragment.kt:344)
        at org.kiwix.kiwixmobile.nav.destination.reader.KiwixReaderFragment.onViewCreated(KiwixReaderFragment.kt:77)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at org.kiwix.kiwixmobile.core.main.CoreMainActivity.onStart(CoreMainActivity.kt:107)
        at org.kiwix.kiwixmobile.main.KiwixMainActivity.onStart(KiwixMainActivity.kt:135)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8195)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3805)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8280)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
`

* If we remove ```@SuppressLint("SoonBlockedPrivateApi")```  (for supressing lint) then it shows error for android 13 and above (and now we are targeting android 13). 

![Screenshot from 2023-02-08 17-41-16](https://user-images.githubusercontent.com/34593983/217526315-3e15a848-f2d9-4749-b495-18799cc6b186.png)


*  We can not use [Calligraphy2](https://github.com/chrisjenx/Calligraphy) because it's not maintainable as they mention on their repo description (they suggest to use [Calligraphy3](https://github.com/InflationX/Calligraphy) but it's not working on our scenario we can set only statically one font in whole app).

* I have find some other alternative of this library. but no one work as expected.
* So i have added custom code for changing font, rest of this i will update on the PR description.
