### ISSUE TITLE
Wikimed crashes on Samsung galaxy A12 with an Android version 12

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3902]
Here is the feedback sent by our user:

> When ever I try to open the app it tells me to share  this;
Someone has reported a crash
  Hi Kiwix Developers!
The Android app crashed, here are some details to help fix it:
    
      Exception Details:
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = kotlinx.coroutines.CoroutinesInternalError)
	at android.os.Parcel.writeSerializable(Parcel.java:2178)
	at android.os.Parcel.writeValue(Parcel.java:1944)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.content.Intent.writeToParcel(Intent.java:11771)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2867)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1135)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1106)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:420)
	at org.kiwix.kiwixmobile.core.main.CoreMainActivity$$ExternalSyntheticLambda0.uncaughtException(R8$$SyntheticClass:35)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:73)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:15)
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:51)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:170)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: Em

**Comment by kelson42** [comment]
@Popolechien Its really important that users which want a fix open the issue themself.
