### ISSUE TITLE
The Zimit `100 Rabbits` ZIM file is not found on the server.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#4020]
**Describe the bug**
When I download the `100 Rabbits` ZIM file it gives giving 404 error. But this ZIM file is present in the `library.xml` file. 

The URL is https://download.kiwix.org/zim/zimit/100r.co_en_all_2024-10.zim.meta4

**Steps to reproduce the behavior:**
1. Open the application, and go to the Download screen.
2. Click on the `100 Rabbits` ZIM file, and you will see the error(Download will not start).
![Image](https://github.com/user-attachments/assets/dd7b82f3-8838-41f1-8a18-d91b2af6f2d2)

![Image](https://github.com/user-attachments/assets/1cbbacfe-1a6d-4827-b095-157102e573d5)

**Logs**
```kotlin
22:38:57.539  9548-10249 okhttp.OkHttpClient     org.kiwix.kiwixmobile                I  <-- 404 https://download.kiwix.org/zim/zimit/100r.co_en_all_2024-10.zim.meta4 (388ms, 196-byte body)
2024-10-04 22:38:57.541  9548-10249 System.err              org.kiwix.kiwixmobile                W  retrofit2.adapter.rxjava2.HttpException: HTTP 404 
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-10-04 22:38:57.544  9548-10249 System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
```

**Comment by MohitMaliFtechiz** [comment]
@rgaudin Can you please have a look at this issue?

**Comment by MohitMaliFtechiz** [comment]
Something has happened in the past two hours since I was able to download this ZIM file two hours ago. Also, this file was downloaded in our test cases in CI [Here](https://github.com/kiwix/kiwix-android/pull/4019). Maybe this clue will be helpful as we have changed something somewhere in the last two hours.

**Comment by MohitMaliFtechiz** [comment]
The issue is now fixed, the ZIM file is now started downloading.

![Image](https://github.com/user-attachments/assets/06dc9670-bbe6-49de-81cc-ad173204b83e)
