### ISSUE TITLE
If left on full screen and exited from app, the app crashes when opened again.

### ISSUE THREAD

**Issue by suyash0103** [kiwix/kiwix-android#502]
**Is it a ?**

- [✔️ ] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [✔️ ] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : Android Studio 3.0.1
  * device / operating system : Motorola Moto M, Android 7
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
Crash in app.

  * When does this occur? 
When user exits the app from full screen mode, and opens the app again.

#### Steps to reproduce:

  1. Enable full screen mode from settings.
  2. Close the app.
  3. Open the app.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
App should not crash.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by suyash0103** [comment]
StackTrace:

FATAL EXCEPTION: main
Process: org.kiwix.kiwixcustomexample, PID: 20542
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixcustomexample/org.kiwix.kiwixmobile.KiwixMobileActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2737)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2806)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:203)
    at android.app.ActivityThread.main(ActivityThread.java:6293)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1065)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
    at org.kiwix.kiwixmobile.KiwixMobileActivity.openFullScreen(KiwixMobileActivity.java:893)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.loadPrefs(KiwixMobileActivity.java:1648)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.selectTab(KiwixMobileActivity.java:791)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.newTab(KiwixMobileActivity.java:730)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.newTab(KiwixMobileActivity.java:724)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.getCurrentWebView(KiwixMobileActivity.java:803)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.openArticle(KiwixMobileActivity.java:1342)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.openMainPage(KiwixMobileActivity.java:1356)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.openZimFile(KiwixMobileActivity.java:1012)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.restoreTabStates(KiwixMobileActivity.java:1710)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState(KiwixMobileActivity.java:1749)
    at org.kiwix.kiwixmobile.KiwixMobileActivity.onCreate(KiwixMobileActivity.java:454)
    at android.app.Activity.performCreate(Activity.java:6674)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
