### ISSUE TITLE
Kiwix crashes when search button is pressed

### ISSUE THREAD

**Issue by RohanBh** [kiwix/kiwix-android#585]
### Are you ready to report?
   Yes
### Environment
  * version of the software you use : v2.3 Build:55(latest build from master, commit cf4187f)
  * device / operating system : oneplus 3, Android 8.0
  
### The Bug:
  
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.search.SearchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.kiwix.kiwixmobile.utils.SharedPreferenceUtil.getPrefNightMode()' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.kiwix.kiwixmobile.utils.SharedPreferenceUtil.getPrefNightMode()' on a null object reference
                                                                         at org.kiwix.kiwixmobile.search.SearchActivity.onCreate(SearchActivity.java:60)
                                                                         at android.app.Activity.performCreate(Activity.java:6998)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
```

#### Steps to reproduce:

  1. Tap on the search icon in the Action bar
 

**UPDATE:** I noticed that even after fixing the crash, a bug still remains. The [AutoCompleteAdapter](https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java) won't populate the list that displays search items. The `mData` variable that stores the list now always contains a list of size 0 in the method [publishResults()](https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/views/AutoCompleteAdapter.java#L124).
Since this is very closely related to the current issue, I am not creating a separate issue for the same. Another reason for not creating another issue is that this issue surfaces only when the crash is resolved.

**Comment by kelson42** [comment]
@RohanBh I can not reproduce this crash. Does that happen only under certain conditions (not listed in the ticket?)

**Comment by GeVic** [comment]
@RohanBh  I know why it is happening. It is because of the recent merges in the searchactivity

**Comment by GeVic** [comment]
@RohanBh There is SharedPreferenceUtil import which can't be resolve and so the app crashes as clicked on search.
I can resolve it. should i?

**Comment by RohanBh** [comment]
No it happens always @kelson42. It is happening in the latest build.
I know @GeVic.Thanks anyways.

**Comment by RohanBh** [comment]
@Gevic I have already made a PR.

**Comment by GeVic** [comment]
@RohanBh  oh i didn't notice it.

**Comment by GeVic** [comment]
@RohanBh if you don't mind can you tell me how setupDagger() stopped the crash. 
Thanks

**Comment by RohanBh** [comment]
`setUpDagger()` is the method where we use the component to inject the dependencies into the class. `sharedPreferenceUtils` is one of such dependency. Calling a `SharedPreferenceUtils.java` class' method through `sharedPreferenceUtils` variable without instantiating it produces a `NPE`.

**Comment by srv-twry** [comment]
Ah! my mistake. Thank you.
BDW Can you please do a quick check in all the classes which use SharedPreferenceUtil whether injection is done properly ? 
I checked it and was also checked by others during PR review but may be we missed one or two.

**Comment by srv-twry** [comment]
For the list of files you can see my PR #515

**Comment by RohanBh** [comment]
I did check your PR before.
