### ISSUE TITLE
Search bar crashes the app

### ISSUE THREAD

**Issue by GeVic** [kiwix/kiwix-android#665]
# For a Bug Report:
- [ ] Feature Request
- [x] Bug Report 

### Are you ready to report?
- [x] Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use : **3.0.1**
  * device / operating system : **Huwawei BLN-L22 (Android 7.0 API 24 )**
  
#### Steps to reproduce:

1. Click on **search bar** in online tab.
2. **Wait until the online list gets displayed.**
2. While still typing, click outside the keyboard app.
4. App crashed to the another activity (Main page reloads).

- Similar issue has already been reported(#311) but this crash happens with any search and not just with any specific word.

It happened 4/5 time for me.

@mhutti1 @rashiq @srv-twry Can anyone of you confirm this?

**Comment by RohanBh** [comment]
I am confirming the crash @Gevic. Actually, for me it doesn't matter if the list is loading or not,  the app always crashes even if I skip the 2nd point.

**Comment by GeVic** [comment]
Ok then, I'll look into it and will create a PR asap.

**Comment by kelson42** [comment]
@GeVic Thx, this to me an important bug to fix. Many users reported that under certain condition the app was crashing by making searches.

**Comment by GeVic** [comment]
@kelson42 The exceptions that we are getting on the crash is `java.io.IOException: write failed: EPIPE (Broken pipe)`
And so I think the problem is file size.

**Comment by GeVic** [comment]
@kelson42 I got the below error once and it's related to `leakcanary`
![screenshot_20180326-214758](https://user-images.githubusercontent.com/29516629/37920075-78da454a-3143-11e8-8a42-3c449192151e.png)

**Comment by GeVic** [comment]
@kelson42 So, The app crashes because of the LIstVIew Modifications. 
```
FATAL EXCEPTION: main
                                                                       Process: org.kiwix.kiwixmobile, PID: 19849
                                                                       java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131296392, class android.widget.ListView) with Adapter(class org.kiwix.kiwixmobile.library.LibraryAdapter)]
                                                                           at android.widget.ListView.layoutChildren(ListView.java:1623)
                                                                           at android.widget.AbsListView$CheckForTap.run(AbsListView.java:3504)
                                                                           at android.os.Handler.handleCallback(Handler.java:761)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by GeVic** [comment]
I am closing this issue as it's currently active as #311 and #315.
