### ISSUE TITLE
[bug] Online ZIM list fails to repopulate after device rotates

### ISSUE THREAD

**Issue by Raghav-intrigue** [kiwix/kiwix-android#667]
### Environment
  * version of the software you use: Kiwix Official 2.2
  * device / operating system : Oneplus X (6.0.1)
  
### The Bug:

  * The list of online ZIMs fail to load after rotating the device.

![p1](https://user-images.githubusercontent.com/12858001/37876905-03308b56-3071-11e8-9411-c4a291f151f6.jpeg)
![p2](https://user-images.githubusercontent.com/12858001/37876907-036c3fca-3071-11e8-898e-cc436af1eeb6.jpeg)
![p3](https://user-images.githubusercontent.com/12858001/37876908-03a86ba8-3071-11e8-8bfd-f3326fe4d319.jpeg)

* As you can see from the timestamps on the screenshots, even after 3 minutes the list had not loaded.
* When does this occur? 
  When the device is rotated after the list is fully populated. The list fails to download and does not load even after rotating back.

#### Steps to reproduce:

  1. Go to Library, to the online tab and wait for the list to load.
  2. Rotate your device to horizontal mode.
  3. The list does not populate even after waiting for a long time.
  4. Rotating back does not help either.
  ...
  
  * What should be the behavior from your point of view? How do you expect the service to work?
 The list should repopulate instantly as it has already downloaded the results before and should not lead to a redownload in the first place.

**Comment by kelson42** [comment]
Is that not a duplicate of #559 and #608?

**Comment by Raghav-intrigue** [comment]
No @kelson42, the issue I've reported points to the inability of the app to repopulate the list on rotation. #559 and #608 focus on avoiding the redownload of the list.

**Comment by Raghav-intrigue** [comment]
Apparently, the activity doesn't have a call to unregister receiver and due to the leaked receiver, the activity crashes when the view is destroyed and created again on rotation.  
Can I get assigned to this? 
The error log has been attached for your reference: 
`03-25 22:47:34.087 31155-31155/? E/ActivityThread: Activity org.kiwix.kiwixmobile.ZimManageActivity has leaked IntentReceiver org.kiwix.kiwixmobile.LibraryFragment$NetworkBroadcastReceiver@249a01c that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                   android.app.IntentReceiverLeaked: Activity org.kiwix.kiwixmobile.ZimManageActivity has leaked IntentReceiver org.kiwix.kiwixmobile.LibraryFragment$NetworkBroadcastReceiver@249a01c that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                       at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:946)
                                                       at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:742)
                                                       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1188)
                                                       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1168)
                                                       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1162)
                                                       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:555)
                                                       at org.kiwix.kiwixmobile.LibraryFragment.onCreateView(LibraryFragment.java:119)
                                                       at android.app.Fragment.performCreateView(Fragment.java:2220)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                       at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
                                                       at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:562)
                                                       at android.support.v13.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:149)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1237)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1085)
                                                       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1611)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5959)
                                                       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:671)
                                                       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1319)
                                                       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:736)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5959)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5959)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5959)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5959)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5959)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2649)
                                                       at android.view.View.measure(View.java:18852)
                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2107)
                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1223)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1459)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1114)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6068)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                   	at`

**Comment by hjoshi123** [comment]
@Raghav-intrigue Refer to this PR https://github.com/kiwix/kiwix-android/pull/652 . I have attempted to solve it and its improved.

**Comment by Raghav-intrigue** [comment]
Alright. Closed then.
