### ISSUE TITLE
Test fails with "Unable to start activity" on TestDroid 

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#699]
A test fails consistently in TestDroid. It's been failing since Test run 1196 and since 05.04.2018 13:33:25 (their timestamp). So far it's failed 17 times in succession.

Out of curiosity I notice the device being used is an Samsung S6 running Android 6.0.1 instead of the Samsung S7 running Android 7 which we used until late March. I _doubt_ this is the reason, however the change of device might be a factor in exposing the problem? To be clear, the tests did run successfully on the S6 e.g. Test Run 1190 on 01.04.2018 23:31:44 (and various others before and afterwards).

Clues:

- The previous tests consisted of 11 tests, from this test run onwards only 2 tests are run: 
1 testMigrateDatabase (passes)
2 basicTest (fails)

I don't know whether the other 9 tests aren't run because of the failing test (i.e. a test runner decides not to run the next set(s) of tests) or because someone's changed the configuration and/or build target somehow e.g. is it somehow related to https://github.com/kiwix/kiwix-android/issues/692 ?

- the error log states the cause is:
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: 
"/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:56)
```
BTW: I split the relevant line so it's easier to spot the message about 32-bit instead of 64-bit.

Here is the complete error log for the failing test taken from TestDroid
```
/**
 * Samsung Galaxy S6 SM-G920F
 */

//--------------------------------------------------------//
//
// 2. basicTest
//

// Stacktrace
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
at android.app.ActivityThread.access$1100(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:169)
at android.webkit.WebView.getFactory(WebView.java:2290)
at android.webkit.WebView.ensureProviderCreated(WebView.java:2285)
at android.webkit.WebView.setOverScrollMode(WebView.java:2344)
at android.view.View.<init>(View.java:4049)
at android.view.View.<init>(View.java:4169)
at android.view.ViewGroup.<init>(ViewGroup.java:589)
at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
at android.webkit.WebView.<init>(WebView.java:609)
at android.webkit.WebView.<init>(WebView.java:554)
at android.webkit.WebView.<init>(WebView.java:537)
at android.webkit.WebView.<init>(WebView.java:524)
at org.kiwix.kiwixmobile.views.web.KiwixWebView.<init>(KiwixWebView.java:125)
at org.kiwix.kiwixmobile.views.web.ToolbarStaticKiwixWebView.<init>(ToolbarStaticKiwixWebView.java:37)
at org.kiwix.kiwixmobile.KiwixMobileActivity.getWebView(KiwixMobileActivity.java:730)
at org.kiwix.kiwixmobile.KiwixMobileActivity.newTab(KiwixMobileActivity.java:745)
at org.kiwix.kiwixmobile.KiwixMobileActivity.newTab(KiwixMobileActivity.java:741)
at org.kiwix.kiwixmobile.KiwixMobileActivity.getCurrentWebView(KiwixMobileActivity.java:820)
at org.kiwix.kiwixmobile.KiwixMobileActivity.showHelpPage(KiwixMobileActivity.java:949)
at org.kiwix.kiwixmobile.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState(KiwixMobileActivity.java:1828)
at org.kiwix.kiwixmobile.KiwixMobileActivity.onCreate(KiwixMobileActivity.java:458)
at android.app.Activity.performCreate(Activity.java:6876)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:624)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
... 9 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:163)
... 33 more
Caused by: java.lang.RuntimeException: Cannot load WebView
at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:66)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:31)
... 35 more
Caused by: org.chromium.base.library_loader.ProcessInitException
at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:72)
at org.chromium.base.library_loader.LibraryLoader.loadNowOverrideApplicationContext(LibraryLoader.java:26)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:60)
... 36 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:56)
... 38 more


// Error message
Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
```

**Comment by julianharty** [comment]
I think I've managed to track the problem down to an old version of the Android System WebView on the particular device we happen(ed) to be using on TestDroid/Bitbar. I managed to connect to that device interactively and update the WebView in Google Play and the tests have now run successfully.

![0](https://user-images.githubusercontent.com/785891/38690243-8a4a130c-3e75-11e8-85e0-744097e05a31.png)

![1](https://user-images.githubusercontent.com/785891/38690247-8e1a8822-3e75-11e8-870b-f6e147475558.png)

![2](https://user-images.githubusercontent.com/785891/38690254-91bf9f76-3e75-11e8-9951-7971ad8e53ca.png)

**Comment by julianharty** [comment]
A quick update. Last night's builds all ran successfully but the automated tests failed with a similar error on TestDroid this morning (13 April 2018). I discovered another update was pending for the Android System WebView component which I applied on the device. I was then able to run Kiwix again on it and the automated tests also completed. I'm contacting bitbar support to see how we can best resolve the problems on this and perhaps similar devices. I'll update this ticket when we have made more progress.
![4](https://user-images.githubusercontent.com/785891/38730597-0b29ca6e-3f0f-11e8-8f35-0d07780f0596.png)

**Comment by julianharty** [comment]
The support team at Bitbar updated the Android System WebView control on Friday 13th April 2018. This seems to have cured the issue. Closing this issue for now. I'll reopen it if the problem reoccurs in the coming days, otherwise we can open a new ticket and refer back to this one.
