### ISSUE TITLE
A possible restriction on 4.4 devices? io.reactivex.exceptions.OnErrorNotImplementedException: database is locked (code 5)

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-android#800]
Note this happened during one of the test runs, shortly after I'd removed the older Android 4.1 device to leave the remaining 4. At the moment I'm recording it so we have a record of the issue. I noticed many more of our tests failed on the older Android version (4.1) I'd like us to be able to test comprehensively and reliably on any/all the Android versions we want to support.

**Describe the bug**
One of the automated tests failed:

`Instrumentation run failed due to 'android.database.sqlite.SQLiteDatabaseLockedException'`

**Expected behavior**
All tests should pass on all devices. Those that aren't intended to run on older Android revisions should be filtered out using annotations in the source code in the Espresso tests (or whatever we're using).

**Steps to reproduce the behavior:**
Run the automated tests on bitbar (run by starting/restarting the build in Travis-CI)

**Environment**
- Version of Kiwix Android : HEAD (bitbar test session 1478)
- Device : Lenovo Lemon K3 K30T
- OS version : 4.4

**Logs**
```
io.reactivex.exceptions.OnErrorNotImplementedException: database is locked (code 5)
at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:88)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:160)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:472)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:419)
at android.support.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:404)
at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:49)
at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:128)
at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)
at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5237)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:813)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1365)
at com.yahoo.squidb.data.adapter.SQLiteDatabaseAdapter.insertOrThrow(SQLiteDatabaseAdapter.java:158)
at com.yahoo.squidb.data.SquidDatabase.insert(SquidDatabase.java:592)
at com.yahoo.squidb.data.SquidDatabase.insertRow(SquidDatabase.java:1687)
at com.yahoo.squidb.data.SquidDatabase.persistWithOnConflict(SquidDatabase.java:1623)
at com.yahoo.squidb.data.SquidDatabase.persist(SquidDatabase.java:1608)
at org.kiwix.kiwixmobile.database.NetworkLanguageDao.saveFilteredLanguages(NetworkLanguageDao.java:66)
at org.kiwix.kiwixmobile.library.LibraryAdapter.lambda$saveNetworkLanguages$2(LibraryAdapter.java:473)
at org.kiwix.kiwixmobile.library.-$$Lambda$LibraryAdapter$MDW_Fg4XtwBjjjGbsXgUMaSHI2o.run(lambda)
at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
at io.reactivex.Completable.subscribe(Completable.java:1794)
at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:463)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by abdulwd** [comment]
@julianharty Does this bug exist in branch 3.0?

**Comment by kelson42** [comment]
Bitbar not being part anymore of the CI, this problem will be difficult to reproduce. But if this is still a problem with 3.0 we will see it in the play store.
