### ISSUE TITLE
Test Language Activity Fails

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#818]
**Describe the bug**
testLanguageActivity

**Expected behavior**
Test fails on Galaxy S8

**Environment**
- Version of Kiwix Android : 3.0
- Device : Samsung Galaxy S8
- OS version : 8.0

```
    Process: org.kiwix.kiwixmobile, PID: 11103
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at org.kiwix.kiwixmobile.data.local.dao.BookDao.saveBooks(BookDao.java:124)
        at org.kiwix.kiwixmobile.data.Repository.saveBooks(Repository.java:87)
        at org.kiwix.kiwixmobile.main.MainPresenter.saveBooks(MainPresenter.java:57)
        at org.kiwix.kiwixmobile.main.MainActivity$1.onScanCompleted(MainActivity.java:250)
        at org.kiwix.kiwixmobile.utils.files.FileSearch.checkCompleted(FileSearch.java:79)
        at org.kiwix.kiwixmobile.utils.files.FileSearch.lambda$scan$0(FileSearch.java:65)
        at org.kiwix.kiwixmobile.utils.files.-$$Lambda$FileSearch$noMoKTYjhiK9PrPtpf1sy9G1gFU.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by julianharty** [comment]
@mhutti1 just checking - do you actually expect the test to fail? 

What is a pass intended to indicate? ie if the test passes what have we learned about the behaviour of the app?

**Comment by siddharth2010** [comment]
@julianharty this is a UI test that tests all of the UI interactions that the user can perform in the language activity and verifies that that the app behaviour is as expected.
this includes tests like 'searching for a language, selecting it, and then clicking cross, and verifying that the language is not selected'
And no. the tests is expected to pass. However it is failing.
