### ISSUE TITLE
wikipedia_en_all_novid_2018-06.zim causes crash when scaning SD card for zim files

### ISSUE THREAD

**Issue by Stevko-sk** [kiwix/kiwix-android#820]
When I open _Get content_ menu item kiwix starts scanning for zim files. It shows some of them and then I get Android message Kiwix has stopped. The next one it would show would be wikipedia – when I remove wikipedia zim file, other files show up and work as expected.

**Expected behavior**
I expect all zim files to show in the menu and then open when clicked

**Steps to reproduce the behavior:**
1. Run kiwix
2. Got to menu, select Get Content
3. Allow access to files.
4. Some zim files start to show up. Then kiwix crashes.

**Environment**
- Version of Kiwix Android : Nightly from https://download.kiwix.org/nightly/2018-07-23/kiwix-android_arm-debug.apk (same happens with 2.3 from https://download.kiwix.org/bin/android/2.3/)
- Device : Lenovo K33a42 (also known as Lenovo K6 Power)
- OS version : 7.0
- zim file:  wikipedia_en_all_novid_2018-06.zim (sha1: 941825f215ea5ca0edf19f6e1f59ac92c9acaa5e, computed on device, matches one from the computer where it was downloaded using torrent)

**Logs**
[kiwixcrash.log](https://github.com/kiwix/kiwix-android/files/2224342/kiwixcrash.log) (hopefully all relevant parts)

**Comment by mhutti1** [comment]
Hi @Stevko-sk this could possibly be the key to solving a large amount of crashes. Many thanks for the log, specifically this section 👍 

```
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0x90f79660
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]     from java.lang.String org.kiwix.kiwixlib.JNIKiwixReader.getFavicon()
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470] "Thread-6" prio=5 tid=46 Runnable
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x13b7b820 self=0x8f9ed800
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   | sysTid=7209 nice=0 cgrp=default sched=0/0 handle=0x90f7a920
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 1373979410 135773652 2131 ) utm=76 stm=61 core=2 HZ=100
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   | stack=0x90e78000-0x90e7a000 stackSize=1038KB
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #00 pc 0034cdb1  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #01 pc 0032d771  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+308)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #02 pc 0023735d  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+848)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #03 pc 002378f3  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #04 pc 003311d7  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+302)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #05 pc 003f000b  /system/lib/libart.so (_ZN3art25JniMethodEndWithReferenceEP8_jobjectjPNS_6ThreadE+30)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   native: #06 pc 000649db  /data/app/org.kiwix.kiwixmobile-1/oat/arm/base.odex (Java_org_kiwix_kiwixlib_JNIKiwixReader_getFavicon__+86)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixlib.JNIKiwixReader.getFavicon(Native method)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixmobile.ZimContentProvider.getFavicon(ZimContentProvider.java:226)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixmobile.utils.files.FileSearch.fileToBook(FileSearch.java:190)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   - locked <0x0862ff9c> (a java.lang.Class<org.kiwix.kiwixmobile.utils.files.FileSearch>)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixmobile.utils.files.FileSearch.onFileFound(FileSearch.java:225)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixmobile.utils.files.FileSearch.scanMediaStore(FileSearch.java:100)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixmobile.utils.files.FileSearch.lambda$scan$1(FileSearch.java:70)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at org.kiwix.kiwixmobile.utils.files.-$$Lambda$FileSearch$h9nbRxww9u8149lRNNLajn7DSVk.run(lambda:-1)
07-24 17:03:28.894  7109  7209 F art     : art/runtime/java_vm_ext.cc:470]   at java.lang.Thread.run(Thread.java:761)
```

**Comment by mhutti1** [comment]
@Stevko-sk Can you confirm this is fixed in the latest rollout release with https://github.com/kiwix/kiwix-lib/pull/159 in it?

**Comment by Stevko-sk** [comment]
Opened #824

**Comment by kelson42** [comment]
@Stevko-sk Thank you, I close this one then
