### ISSUE TITLE
App crash upon switching from wifi to mobile data while downloading 

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#883]
**Describe the bug**

When download mode is changed from wifi to mobile data after pausing the download, and download is restarted, app crashes (Initially, download using wifi data only is toggled **ON**).

**Expected behavior**

Once download using wifi only is turned **OFF** and wifi is turned off while mobile data is on, download connection should not break and should continue downloading.

**Steps to reproduce the behavior:**
1. Download using wifi only mode should be **ON**.
2. Start downloading using wifi.
3. The download is paused and wifi is turned off keeping mobile data on.
4. The download is restarted. Since wifi is turned off, it requests for downloading via the mobile network.
If selected yes, the app crashes. And even if the download is stopped instead of restarting, the app crashes
(If Download only using wifi is toggled off initially, this does not happen).

![kiwix crash gif](https://user-images.githubusercontent.com/34706326/47607693-e0dad500-da40-11e8-9ce5-22f99525c75c.gif)

**Screenshots**

**Environment**
- Version of Kiwix Android: 2.4 Build 1182160
- Device: Redmi 4
- OS version : 7.1.2

**Logs**

 java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.utils.SharedPreferenceUtil.putPrefWifiOnly(boolean)' on a null object reference
        at org.kiwix.kiwixmobile.downloader.DownloadFragment.lambda$showNoWiFiWarning$0(DownloadFragment.java:122)
        at org.kiwix.kiwixmobile.downloader.-$$Lambda$DownloadFragment$AJs1OHPtJjncqkd4vcwQcB1k8zQ.onClick(lambda)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**I would request you to please assign me for this issue.**

**Comment by macgills** [comment]
Fixed in #1170
