### ISSUE TITLE
Upon closing all the tabs and pressing back button , app crashes.

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#891]
**Describe the bug**

App crashes when all tabs are closed and back button is pressed

**Expected behavior**

The app should just exit without crashing.

**Steps to reproduce the behavior:**

1. Open two or more tabs are open.
2. Close all tabs using CloseAllTabs or swiping up for all tabs.
3. Press back button.

**Screenshots**

![kiwix crash 3 gif](https://user-images.githubusercontent.com/34706326/48331904-cf680e80-e677-11e8-9354-f798fc6c6961.gif)

**Environment**
- Device : Redmi 4
- OS version : Android 7.1.2

**Logs**

2018-11-12 12:22:03.996 24644-24644/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 24644
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.main.AnimatedProgressBar.setProgress(int)' on a null object reference
        at org.kiwix.kiwixmobile.main.MainActivity.webViewProgressChanged(MainActivity.java:1775)
        at org.kiwix.kiwixmobile.main.KiwixWebChromeClient.onProgressChanged(KiwixWebChromeClient.java:33)
        at xq.a(SourceFile:47)
        at alW.handleMessage(SourceFile:81)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Request**
Please assign me for this issue.

**Comment by abdulwd** [comment]
@sonusourav Do you have any updates on progress made?

**Comment by sonusourav** [comment]
> 
> 
> @sonusourav Do you have any updates on progress made?

@abdulwd Due to end sem exams, not much progress is there. Exams will be over by 4th Dec and then I will try to do at the earliest.

**Comment by prat-bphc52** [comment]
Appears to be a case of error handling. I shall try to reproducing the error and check out thoroughly what's causing the error. Hopefully it shall not take much time to get it resolved.  . Can I get to work on this issue?
