### ISSUE TITLE
App crashes on toggling on/off all settings switches 

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#895]
**Describe the bug**

When you toggle on/off all the settings switches all at a time, app crashes. This may not happen when you do for the first time but probably in the second or third time.

**Expected behavior**

The app should not crash.

**Steps to reproduce the behavior:**

1. Open the settings page.
2. Toggle on/off all switches at once.
3. Press the back button.
4. Repeat it one or two times and app crashes.

**Screenshots**

![kiwix crash 6 gif](https://user-images.githubusercontent.com/34706326/48442357-06dbd580-e7b4-11e8-81a2-eb1fe6033700.gif)

**Environment**
- The version of Kiwix Android: Build 2.4
- Device: Redmi 4
- OS version: Android 7.1

**Logs**

2018-11-14 02:04:59.395 2900-2900/org.kiwix.kiwixmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kiwix.kiwixmobile, PID: 2900
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kiwix.kiwixmobile.main.AnimatedProgressBar.setProgress(int)' on a null object reference
        at org.kiwix.kiwixmobile.main.MainActivity.webViewProgressChanged(MainActivity.java:1779)
        at org.kiwix.kiwixmobile.main.KiwixWebChromeClient.onProgressChanged(KiwixWebChromeClient.java:33)
        at xq.a(SourceFile:47)
        at alW.handleMessage(SourceFile:81)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by siddharth2010** [comment]
Hey @sonusourav , I am not able to reproduce this issue right now. Are you still getting it?

**Comment by sonusourav** [comment]
@siddharth I am still getting it.

**Comment by abdulwd** [comment]
I sometimes get this type of crash on the first run when I change the night mode and press back. You can add a simple null check.
